name: "UTE Consumo"
version: "1.2.1"
slug: "ute_consumo"
description: "Scraper de consumo de energ√≠a UTE (Uruguay)"
url: "https://github.com/matiasca89/hacs-ute"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  username: ""
  password: ""
  account_id: ""
  scan_interval: 60
schema:
  username: str
  password: str
  account_id: str
  scan_interval: int
homeassistant_api: true
